# The Conventional Commits toolbox
# see: https://github.com/cocogitto/cocogitto

# All version numbers should be prefixed with v to denote
# a version number over anything other type of tag
tag_prefix = "v"

# Only releases from master are allowed
branch_whitelist = ["master"]

# Check commit history, starting from the latest tag to HEAD
from_latest_tag = true

# We don't need a root level CHANGELOG or tag for this monorepo
generate_mono_repository_global_tag = false

# Make sure our git identity is configured
pre_bump_hooks = [
  "git config --global user.email github-actions[bot]@users.noreply.github.com",
  "git config --global user.name github-actions[bot]",
]

# Publish artifacts, push up the changelogs & tags
post_bump_hooks = [
  "devcontainer features publish -n brad-jones/pixi-devcontainer ./features/src",
  "devcontainer templates publish -n brad-jones/pixi-devcontainer ./templates/src",
  "git push",
  "git push --tags",
]

# Create a CHANGELOG that includes helpful links to github diffs / commits / PRs, etc.
[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "brad-jones"
repository = "pixi-devcontainer"
authors = [
  { signature = "Brad Jones", username = "brad-jones" },
]

# There should be one entry per publishable and/or deployable artifact in this monorepo
[packages.pixi]
path = "features/src/pixi"
pre_bump_hooks = [
  "rjp devcontainer-feature.json version {{version}} --limit 1",
  "dprint fmt CHANGELOG.md devcontainer-feature.json",
]

[packages.pixi-pre-build]
path = "templates/src/pixi-pre-build"
pre_bump_hooks = [
  "rjp devcontainer-template.json version {{version}} --limit 1",
  "dprint fmt CHANGELOG.md devcontainer-template.json",
]
