[project]
name = "pixi-devcontainer"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
npm-install = "npm install -g npm && npm install"
test = "devcontainer features test"

[dependencies]
shellcheck = ">=0.9.0,<0.10"
go-shfmt = ">=3.7.0,<3.8"
nodejs = ">=20.9.0,<20.10"
