[project]
name = "pixi-devcontainer"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
shellcheck = ">=0.9.0,<0.10"
go-shfmt = ">=3.7.0,<3.8"
nodejs = ">=20.9.0,<20.10"
deno = ">=1.39.1,<1.40"

[tasks]
npm-install = "npm install -g npm && npm install"
test = { depends_on = ["test-features", "test-templates"] }
test-features = "./node_modules/.bin/devcontainer features test ./features"
test-templates = "deno test -A ./templates/test/*.ts"
validate-commits = "./bin/cog check"
release = 'PATH="$PWD/node_modules/.bin:$PATH" ./bin/cog bump --auto'

[tasks.shell]
depends_on = ["npm-install"]
cmd = 'PATH="$PWD/bin:$PWD/node_modules/.bin:$PATH" pixi shell'

[tasks.code]
depends_on = ["npm-install"]
cmd = 'PATH="$PWD/bin:$PWD/node_modules/.bin:$PATH" code .'
