[project]
name = "pixi-devcontainer"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
npm-install = "npm install -g npm && npm install"
test = "./node_modules/.bin/devcontainer features test"
validate-commits = "./bin/cog check"
bump-version = 'PATH="$PWD/node_modules/.bin:$PATH" ./bin/cog bump --auto'

[tasks.publish]
depends_on = ["bump-version"]
cmd = "./node_modules/.bin/devcontainer features publish -n brad-jones/devcontainer-features ./src"

[tasks.shell]
depends_on = ["npm-install"]
cmd = 'PATH="$PWD/bin:$PWD/node_modules/.bin:$PATH" /usr/bin/env bash'

[dependencies]
shellcheck = ">=0.9.0,<0.10"
go-shfmt = ">=3.7.0,<3.8"
nodejs = ">=20.9.0,<20.10"
