on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

permissions:
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pixi Package Manager
        uses: prefix-dev/setup-pixi@v0.4.1
        with:
          locked: true
          cache: true

      - name: Validate Conventional Commits
        run: pixi run validate-commits

      - name: Get path to npm cache dir
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install node modules
        run: pixi run npm-install

      - name: Test Features
        run: pixi run test

      - name: Publish Features
        if: ${{ github.ref == 'refs/heads/master' }}
        run: pixi run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
